-d C:\Users\franco\Documents\led_switching\impl\gwsynthesis\led_switching.vg
-p GW1N-9C-LQFP144-6
-pn GW1N-UV9LQ144C6/I5
-cst C:\Users\franco\Documents\led_switching\src\led_switching.cst
-cfg C:\Users\franco\Documents\led_switching\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
